[package]
name = "faxina-cli"
version = "0.1.0"
edition = "2021"
description = "Faxina CLI — Limpa pastas de dependências de projetos inativos"

[dependencies]
clap = { version = "4", features = ["derive"] }
colored = "2"
walkdir = "2"
dialoguer = "0.11"
indicatif = "0.17"
jwalk = "0.8.1"
