name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64-musl
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            bin: faxina-cli
            name: faxina-cli-x86_64-linux-musl.tar.gz
            command: tar

          - release_for: Linux-aarch64-musl
            os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            bin: faxina-cli
            name: faxina-cli-aarch64-linux-musl.tar.gz
            command: tar

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: faxina-cli.exe
            name: faxina-cli-Windows-x86_64.zip
            command: zip

          - release_for: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: faxina-cli
            name: faxina-cli-macOS-x86_64.tar.gz
            command: tar

          - release_for: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            bin: faxina-cli
            name: faxina-cli-macOS-aarch64.tar.gz
            command: tar

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (Linux Musl)
        if: contains(matrix.platform.target, 'musl')
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools

      - name: Install Rust-stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.platform.target }}

      - name: Upload Binary
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: faxina-cli
          target: ${{ matrix.platform.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
